version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-docker:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - setup_remote_docker
      - run: npm run build:docker:ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm ci
      - run: npm run lint
      # Save workspace for subsequent jobs
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - build-docker:
          requires:
            - build
